{snippet grid}

    {foreach $flashes as $flash}
        <ul class="message {$flash->type}">
            <li>{$flash->message}</li>
            <li class="close-bt"></li>
        </ul>
    {/foreach}

    {widget $control formBegin}
    {widget $control errors}
    {widget $control navigator}
    {widget $control table}
    {widget $control info}
    {widget $control operations}
    {widget $control formEnd}

{/snippet}
